version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=sample_user
      - MYSQL_PASSWORD=sample_pass
      - MYSQL_ROOT_PASSWORD=sample_root_pass
      - TZ=Asia/Tokyo
    ports:
      - 13306:3306
    container_name: sample-db-server